//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace numberDetector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string MoNumber { get; set; }
        public string email { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
